In [1]:
import mysql.connector as mycon
con = mycon.connect(host="localhost",user="root",password="shelvi31",database="school")

# establishing a connection to the SQLite database by creating a Connection object.

con = mycon.connect(host="localhost2",user="root",password="shelvi31",database="school")

In [2]:
#Defioning add student function

def add_student():
    n = input("Student Name:")
    class_studying = input("class name:")
    roll = input("Roll No:")
    address = input("Address:")
    phone = input("Phone no:")
    
    data = (n,class_studying,roll,address,phone)
    
    
#Next, creating a Cursor object using the cursor method of the Connection object. Then, execute a SELECT statement. 
#After that, call the fetchall() method of the cursor object to fetch the data.
    
    sql = 'INSERT INTO student VALUES(%s,%s,%s,%s,%s)'         #sql query
    c = con.cursor()
    c.execute(sql,data)                             #executing sql query and data in c
    con.commit()
    print("Data Entered Successfully")
    print("--------------------------------------------------------------------------------------------------")

    main()

In [3]:
#Defining remove_student function

def remove_student():
    class_studying = input("class name:")
    roll = input("Roll No:")
    
    data = (class_studying,roll)
    
    sql = 'DELETE FROM student WHERE class_studying=%s and roll=%s'
    c = con.cursor()
    c.execute(sql,data)
    con.commit()
    print("Data Updated")
    print("--------------------------------------------------------------------------------------------------")

    main()

In [4]:
#Defining add teacher function

def add_teacher():
    n = input("Teacher Name:")
    post = input("Teacher Post:")
    salary = input("Teacher's salary:")
    address = input("Address:")
    phone = input("Phone no:")
    acc = input("Teacher's Account")
    
    data = (n,post,salary,address,phone,acc)
    
    sql = 'INSERT INTO teacher VALUES(%s,%s,%s,%s,%s,%s)'            #sql query
    c = con.cursor()
    c.execute(sql,data)                             #executing sql query and data in c
    con.commit()
    print("Data Entered Successfully")
    print("--------------------------------------------------------------------------------------------------")

    main()

In [5]:
#Defining remove_teacher function

def remove_teacher():
    n = input("Teacher Name:")
    acc = input("Teacher's Account")
    
    data = (n,account)
    
    sql = 'DELETE FROM teacher WHERE n=%s and acc=%s'
    c = con.cursor()
    c.execute(sql,data)
    con.commit()
    print("Data Updated")
    print("--------------------------------------------------------------------------------------------------")

    main()

In [6]:
#defining absent in class

def absent_class():
    d = input("Date:")
    class_studying = input("class name:")
    names_absent_student = input("Names of absent students:")
    
    data = (d,class_studying,names_absent_student)
    
    
    sql = 'INSERT INTO cattendance VALUES(%s,%s,%s)'            #sql query
    c = con.cursor()
    c.execute(sql,data)                             #executing sql query and data in c
    con.commit()
    print("Data Updated")
    print("--------------------------------------------------------------------------------------------------")

    main()

In [7]:
#defining absent teachers

def absent_teachers():
    d = input("Date:")
    names_absent_teacher = input("Names of absent teachers:")
    
    data = (d,names_absent_teacher)
    
    
#Next, creating a Cursor object using the cursor method of the Connection object. Then, execute a SELECT statement. 
#After that, call the fetchall() method of the cursor object to fetch the data.
    
    sql = 'INSERT INTO tattendance VALUES(%s,%s)'            #sql query
    c = con.cursor()
    c.execute(sql,data)                             #executing sql query and data in c
    con.commit()
    print("Data Entered Successfully")
    print("--------------------------------------------------------------------------------------------------")

    main()

In [8]:
#defining submmit fees

def submit_fees():
    n = input("Student Name:")
    class_studying = input("class name:")
    roll = input("Roll No:")
    m = input("Month:")
    y = input("Year:")
    fees = input("Fees amount:")
    d = input("Date:")
    
    data = (n,class_studying,roll,m,y,fees,d)
    
    sql = 'INSERT INTO fees VALUES(%s,%s,%s,%s,%s,%s,%s)'
    c = con.cursor()
    c.execute(sql,data)
    con.commit()
    print("Data Entered successfully")
    print("------------------------------------------------------------------------------------------------------")
    
    main()

In [9]:
#defining pay_Salary function

def pay_salary():
    n = input("Teacher Name:")
    m = input("Month: ")
    y = input("Year:")
    stat = input("Payment status : YES/NO")
    
    data = (n,m,y,stat)
    
    sql = 'INSERT INTO salary VALUES(%s,%s,%s,%s)'
    c = con.cursor()
    c.execute(sql,data)
    con.commit()
    print("Data Entered successfully")
    print("------------------------------------------------------------------------------------------------------")
    
    main()

In [10]:
#display class students info

def display_class():
    class_studying = input("Class:")
    data = (class_studying,)
    sql = "SELECT * FROM student WHERE class_studying=%s"
    
    c = con.cursor()
    c.execute(sql,data)
    details = c.fetchall()              #all 5 input values will be fetched
    
    for i in details:
        print("Name:",i[0])
        print("Class:",i[1])
        print("Roll No:",i[2])
        print("Address:",i[3])
        print("Phone:",i[4])
        
    print("-----------------------------------------------------------------------------------------------------------")
                
    main()

In [11]:
#display a teacher's info

def display_teacher():
    n = input("enter the name of teacher you want to fetch info for:")
    data = (name,)
    
    sql = 'SELECT * FROM teacher WHERE n=%s'
    c = con.cursor()
    c.execute(sql)
    details = c.fetchall()
    
    for i in details:
        print("Teacher Name:",i[0])
        print("Post:",i[1])
        print("Salary:",i[2])
        print("Address:",i[3])
        print("Phone:",i[4])
        print("Account number:",i[5])

        print("-------------------------------------------------------------------------------------------------------------")
        
    main()

In [12]:
#Displayiong all teachers information

#display a teacher's info

def display_teachers():
    
    sql = 'SELECT * FROM teacher'
    c = con.cursor()
    c.execute(sql)
    details = c.fetchall()
    
    for i in details:
        print("Teacher Name:",i[0])
        print("Post:",i[1])
        print("Salary:",i[2])
        print("Address:",i[3])
        print("Phone:",i[4])
        print("Account number:",i[5])

        print("-------------------------------------------------------------------------------------------------------------")
        
    main()

In [ ]:
#defining main()

def main():
    
    print("""                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info
                              
                            11. All teachers Info 
                            """)
          

    choice = input("Enter the task you want to execute")

    print("------------------------------------------------------------------------------------------------------------")

    if (choice == "1"):

        add_student()

    elif (choice=="2"):

        remove_student()

    elif (choice=="3"):

       add_teacher()

    elif (choice=="4"):

        remove_teacher()

    elif (choice=="5"):

        absent_class()

    elif (choice == "6"):

        absent_teachers()

    elif (choice=="7"):

        submit_fees()

    elif (choice == "8"):

        pay_salary()

    elif (choice == "9"):

        display_class()

    elif (choice == "10"):

        display_teacher()
          
    elif (choice == "11"):

        display_teachers()

    else:

        print("Please select the correct option")
        main()
          

def pswd():

    p = input("Password :")

    if p == "sms":

        main()

    else:

        print("Wrong Password")

        pswd()

pswd()                    #will call password function first while execution

Password :sms
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute1
------------------------------------------------------------------------------------------------------------
Student Name:shelvi
class name:5 c
Roll No:789
Address:gn
Phone no:8000
Data Entered Successfully
--------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute3
------------------------------------------------------------------------------------------------------------
Teacher Name:rishabh
Teacher Post:professor
Teacher's salary:18L
Address:moradabad
Phone no:9000
Teacher's Accounthfdc 900
Data Entered Successfully
--------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute11
------------------------------------------------------------------------------------------------------------
Teacher Name: rishabh
Post: professor
Salary: 18L
Address: moradabad
Phone: 9000
Account number: hfdc 900
-------------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute11
------------------------------------------------------------------------------------------------------------
Teacher Name: rishabh
Post: professor
Salary: 18L
Address: moradabad
Phone: 9000
Account number: hfdc 900
-------------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute11
------------------------------------------------------------------------------------------------------------
Teacher Name: rishabh
Post: professor
Salary: 18L
Address: moradabad
Phone: 9000
Account number: hfdc 900
-------------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute8
------------------------------------------------------------------------------------------------------------
Teacher Name:rishabh
Month: feburary
Year:2021
Payment status : YES/NOyes
Data Entered successfully
------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute1
------------------------------------------------------------------------------------------------------------
Student Name:mohit
class name:5 c
Roll No:754
Address:chandigarh
Phone no:70009
Data Entered Successfully
--------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute5
------------------------------------------------------------------------------------------------------------
Date:24/02/2021
class name:5 c
Names of absent students:mohit
Data Updated
--------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute6
------------------------------------------------------------------------------------------------------------
Date:24/02/2021
Names of absent teachers:rishabh
Data Entered Successfully
--------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute11
------------------------------------------------------------------------------------------------------------
Teacher Name: rishabh
Post: professor
Salary: 18L
Address: moradabad
Phone: 9000
Account number: hfdc 900
-------------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute3
------------------------------------------------------------------------------------------------------------
Teacher Name:sakshi
Teacher Post:teacher
Teacher's salary:10L
Address:varanasi
Phone no:5009
Teacher's Accounthdfc 500
Data Entered Successfully
--------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute7
------------------------------------------------------------------------------------------------------------
Student Name:shelvi
class name:5 c
Roll No:789
Month:feb
Year:2021
Fees amount:3,000
Date:24/02/2020
Data Entered successfully
------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute9
------------------------------------------------------------------------------------------------------------
Class:5 c
Name: shelvi
Class: 5 c
Roll No: 789
Address: gn
Phone: 8000
Name: mohit
Class: 5 c
Roll No: 754
Address: chandigarh
Phone: 70009
-----------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute11
------------------------------------------------------------------------------------------------------------
Teacher Name: rishabh
Post: professor
Salary: 18L
Address: moradabad
Phone: 9000
Account number: hfdc 900
-------------------------------------------------------------------------------------------------------------
Teacher Name: sakshi
Post: teacher
Salary: 10L
Address: varanasi
Phone: 5009
Account number: hdfc 500
-------------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute1
------------------------------------------------------------------------------------------------------------
Student Name:bunny
class name:6 a
Roll No:80
Address:shamli
Phone no:877
Data Entered Successfully
--------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info

Enter the task you want to execute8
------------------------------------------------------------------------------------------------------------
Teacher Name:sakshi
Month: feburary
Year:2021
Payment status : YES/NOYes
Data Entered successfully
------------------------------------------------------------------------------------------------------
                           GIRRAJ INTERNATIONAL SCHOOL

                            1.  ADD STUDENT                 2.  REMOVE STUDENT

                            3.  ADD TEACHER                 4.  REMOVE TEACHER

                            5. CLASS ATTENDANCE             6.  TEACHER ATTENDANCE

                            7. SUBMIT FEES                  8.  PAY SALARY

                            9. DISPLAY CLASS               10. A TEACHERS Info

                            11. All teachers Info